#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_3key_2us(KC_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_LBRC, KC_RBRC, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_PGUP, KC_LALT, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_EQL, KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_PGDN, KC_BSPC, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSPO, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSPC, KC_LCTL, KC_LGUI, KC_LALT, KC_HOME, MO(3), KC_SPC, KC_BSPC, KC_BSPC, KC_BSPC, MO(3), KC_END, KC_RALT, KC_LGUI, KC_RCTL),
    [1] = LAYOUT_3key_2us(KC_GESC, TO(0), TO(1), TO(2), KC_4, KC_5, KC_LBRC, KC_RBRC, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_PGUP, KC_LALT, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_EQL, KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_PGDN, KC_BSPC, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_LCTL, KC_LGUI, KC_LALT, KC_HOME, MO(3), KC_SPC, KC_BSPC, KC_BSPC, KC_BSPC, MO(3), KC_END, KC_RALT, KC_LGUI, KC_RCTL),
    [2] = LAYOUT_3key_2us(KC_GESC, TO(0), TO(1), TO(2), KC_4, KC_5, KC_LBRC, KC_RBRC, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_PGUP, KC_LALT, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_EQL, KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_PGDN, KC_BSPC, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_LCTL, KC_LGUI, KC_LALT, KC_HOME, TO(3), RGB_TOG, RGB_MOD, KC_BSPC, KC_BSPC, MO(3), KC_END, KC_RALT, KC_LGUI, KC_RCTL),
    [3] = LAYOUT_3key_2us(KC_GRV, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_BSPC, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_PGUP, KC_LALT, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_EQL, KC_CAPS, KC_A, KC_VOLD, KC_VOLU, KC_MUTE, KC_G, KC_PGDN, KC_BSPC, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, LALT(KC_Z), LALT(KC_X), TO(2), KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_LCTL, KC_LGUI, KC_LALT, KC_HOME, MO(3), KC_SPC, KC_BSPC, KC_BSPC, KC_BSPC, MO(3), KC_END, KC_RALT, KC_LGUI, KC_RCTL),
};

const rgblight_segment_t PROGMEM my_capslock_layer[] = RGBLIGHT_LAYER_SEGMENTS(
        {0, 12, HSV_WHITE}       // Light 12 LEDs, starting with LED 0
        );

const rgblight_segment_t PROGMEM my_layer1_layer[] = RGBLIGHT_LAYER_SEGMENTS(
        {9, 3, HSV_CYAN}
        );

const rgblight_segment_t PROGMEM my_layer2_layer[] = RGBLIGHT_LAYER_SEGMENTS(
        {9, 3, HSV_PURPLE}
        );

const rgblight_segment_t PROGMEM my_layer3_layer[] = RGBLIGHT_LAYER_SEGMENTS(
        {9, 3, HSV_GREEN}
        );
const rgblight_segment_t* const PROGMEM my_rgb_layers[] = RGBLIGHT_LAYERS_LIST(
        my_capslock_layer,
        my_layer1_layer,    // Overrides caps lock layer
        my_layer2_layer,     // Overrides other layers
        my_layer3_layer     // Overrides other layers
        );

void keyboard_post_init_user(void) {
    // Enable the LED layers
    rgblight_layers = my_rgb_layers;
}
layer_state_t layer_state_set_user(layer_state_t state) {
    // Both layers will light up if both kb layers are active
    rgblight_set_layer_state(1, layer_state_cmp(state, 1));
    rgblight_set_layer_state(2, layer_state_cmp(state, 2));
    rgblight_set_layer_state(3, layer_state_cmp(state, 3));
    return state;
}

bool led_update_user(led_t led_state) {
    rgblight_set_layer_state(0, led_state.caps_lock);
    return true;
}
